name: "Publish beta release"
on:
  push:
    tags:
    - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - env:
        BUILD_TYPE: beta
        BUILD_SHA: ${{ github.sha }}
      run: env
    - run: "jq '.browser_specific_settings.gecko.id = \"toolbox-beta@toolbox-team.github.com\"' extension/firefox_manifest.json"
    - run: "cat extension/firefox_manifest.json"
